# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Azure Static Web Apps CI/CD for Staging envs

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: CmdLine@2
    inputs:
      script: 'whoami && cd /home/vsts/work/1/s && ls -l'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      api_location: "api"
      verbose: true
      output_location: "build"
      azure_static_web_apps_api_token: $(deploymentToken)
    env:
      RUN_BUILD_COMMAND: "oryx build '/working_dir' --env CUSTOM_BUILD_COMMAND='whoami && pwd && ls -la && npm install --unsafe-perm' -o /ss-oryx/app --manifest-dir /ss-oryx/app-manifest -p require_build -p disable_recursive_lookup=true -p ORYX_APP_TYPE='static-sites' -p NODE_DEFAULT_VERSION=16 -p DOTNET_DEFAULT_VERSION=6 -p PYTHON_DEFAULT_VERSION=3.9"
      CUSTOM_BUILD_COMMAND: 'whoami && pwd && ls -la && npm install --unsafe-perm'
      
