# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Azure Static Web Apps CI/CD for Staging envs

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: CmdLine@2
    inputs:
      script: 'whoami && cd /home/vsts/work/1/s && ls -l'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      api_location: "api"
      verbose: true
      output_location: "build"
      azure_static_web_apps_api_token: $(deploymentToken)
    env:
      CUSTOM_BUILD_COMMAND: 'chown -R root:root . && npm install --unsafe-perm && npm run build'
      
